-- AlterTable
ALTER TABLE "public"."Pet" ALTER COLUMN "activityLevel" DROP NOT NULL,
ALTER COLUMN "chronicDiseases" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "dietType" DROP NOT NULL,
ALTER COLUMN "environmentType" DROP NOT NULL,
ALTER COLUMN "isSterilized" DROP NOT NULL,
ALTER COLUMN "knownAllergies" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "sex" DROP NOT NULL,
ALTER COLUMN "vaccinationUpToDate" DROP NOT NULL,
ALTER COLUMN "weight" DROP NOT NULL;
